import itay1 from './Images/itay1.jpg';
import itay2 from './Images/itay2.jpg';
import itay3 from './Images/itay3.jpg';
import itay4 from './Images/itay4.jpg';
import inOut1 from './Images/inOut1.png';

export const projectsArray = [
    {
        id:1,
        img: itay1,
        role: 'Supervision',
        name: 'Abu Al-Matameer - Wadi Al-Natrun',
        volt: '500 KV',
        length: '134 KM',
        date: '2019',
        category: 'OHTL',
        installation: 'New Installation',
        circuits: 'Double',
        conductor: '4 X 490/65 ACSR',
        insulator: 'Glass',
        details: 'Installation of new 500 KV over head line start from Abu Al-Matameer 500/220/66 k.v substation to Wadi Al-Natrun 500/220/66 k.v substation'
    },
    {
        id:2,
        img: itay1,
        role: 'Supervision Installation',
        name: 'Itay Al-Baroud - Kafr Al-Zyaat',
        volt: '500 KV',
        length: '28 KM',
        date: '2018',
        category: 'OHTL',
        installation: 'New Installation',
        circuits: 'Double',
        conductor: '4 X 490/65 ACSR',
        insulator: 'Porcelain',
        details: 'Installation of new 500 KV over head line start from Abu Al-Matameer 500/220/66 k.v substation to Wadi Al-Natrun 500/220/66 k.v substation'
    },
    {
        id:3,
        img: inOut1,
        role: 'Supervision',
        name: 'Al-Nubaria - Cairo 500 In/Out to Wadi Al-Natrun 500/220/66 KV',
        volt: '500 KV',
        length: '13 KM',
        date: '2018',
        category: 'OHTL',
        installation: 'New Installation',
        circuits: 'Double',
        conductor: '3 X 490/65 ACSR',
        insulator: 'Glass',
        details: '500 KV over head line start from Abu Al-Matameer 500/220/66 k.v substation to Wadi Al-Natrun 500/220/66 k.v substation'
    },
    {
        id:4,
        img: itay4,
        role: 'Supervision',
        name: 'Borolos - Itay Al-Baroud',
        volt: '500 KV',
        length: '105 KM',
        date: '2017',
        category: 'OHTL',
        installation: 'New Installation',
        circuits: 'Double',
        conductor: '4 X 506 AAAC',
        insulator: 'Glass',
        details: '500 KV over head line start from Abu Al-Matameer 500/220/66 k.v substation to Wadi Al-Natrun 500/220/66 k.v substation'
    },
    {
        id:5,
        img: itay3,
        role: 'Supervision Installation, Testing & Commissioning',
        name: 'Main As-Sadat – Main Al-Bustan',
        volt: '220 KV',
        length: '47 KM',
        date: '2016',
        category: 'Fiber Optics',
        installation: 'Life Installation',
        conductor: 'OPGW',
        circuits: 'Double',
        insulator: '',
        details: 'Peplacing old earth wire with new OPGW cable from Main As-Sadat to Main Al-Bustan'
    },
    {
        id:6,
        img: itay3,
        role: 'Supervision Installation, Testing & Commissioning',
        name: 'Main Abu-AlMatameer – Main Al-Bustan',
        volt: '220 KV',
        length: '38 KM',
        date: '2016',
        category: 'Fiber Optics',
        installation: 'Life Installation',
        conductor: 'OPGW',
        circuits: 'Double',
        insulator: '',
        details: 'Peplacing old earth wire with new OPGW cable from Main Abu-AlMatameer to Main Al-Bustan'
    },
    {
        id:7,
        img: itay3,
        role: 'Supervision Installation, Testing & Commissioning',
        name: 'Kafr Al-Zayat – Abo Keer',
        volt: '500 KV',
        length: '100 KM',
        date: '2012',
        category: 'Fiber Optics',
        installation: 'New Installation',
        conductor: 'OPGW',
        circuits: 'Double',
        insulator: '',
        details: 'New Installation of OPGW for 500 k.v line'
    },
    {
        id:8,
        img: itay2,
        role: 'Supervision Installation, Testing & Commissioning',
        name: 'Al-Nubaria PS–SediKreer',
        volt: '500 KV',
        length: '131 KM',
        date: '2009',
        category: 'Fiber Optics',
        installation: 'New Installation',
        conductor: 'OPGW',
        circuits: 'Single',
        insulator: '',
        details: 'New Installation of OPGW for 500 k.v line'
    },
    {
        id:9,
        img: itay2,
        role: 'Supervision Installation, Testing & Commissioning',
        name: 'West Delta Regional Control Center (WDRCC)',
        volt: '220 k.v & 66 k.v',
        length: '94km OPGW, 93km UGOP and 754km ADSS',
        date: '2004 - 2007',
        category: 'Fiber Optics',
        installation: 'New Installation of ADSS,UGOP and Replacement of old earth wire with OPGW',
        conductor: 'OPGW, ADSS and UGOP',
        circuits: 'Double',
        insulator: 'without',
        details: 'New Installation of ADSS Fiber Optics for 66 k.v lines and Replacement of old earth wire with OPGW for 220 k.v'
    },
]