export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const CHANGE_PROJECTS = 'CHANGE_PROJECTS';

export const REQUEST_PROJECTS_PENDING = 'REQUEST_PROJECTS_PENDING';
export const REQUEST_PROJECTS_SUCCESS = 'REQUEST_PROJECTS_SUCCESS';
export const REQUEST_PROJECTS_FAILED = 'REQUEST_PROJECTS_FAILED';